/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { EventEmitter } from "@stencil/core";
export { EventEmitter } from "@stencil/core";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface StnButton {
        "action": EventEmitter<void>;
        "disabled": boolean;
        "icon": boolean;
        "label": string;
        "size": 'small' | 'medium' | 'large';
        "type": 'button' | 'submit';
        "variant": 'primary' | 'secondary' | 'success' | 'warning' | 'info' | 'light' | 'link' | 'outline' | 'danger';
    }
    interface StnModal {
        "buttons": string;
        "customeClass": string;
        "headerTitle": string;
        "isOpen": boolean;
    }
    interface StnModalBottom {
        "closeModal": () => Promise<void>;
        "headerTitle": string;
        "openModal": () => Promise<void>;
        "showFooter": boolean;
    }
    interface StnModalCenter {
        "closeModal": () => Promise<void>;
        "headerTitle": string;
        "openModal": () => Promise<void>;
        "showFooter": boolean;
    }
    interface StnModalSlide {
        "closeModal": () => Promise<void>;
        "confirmModal": () => Promise<void>;
        "headerTitle": string;
        "isConfirm": boolean;
        "openModal": () => Promise<void>;
        "showFooter": boolean;
    }
    interface StnToaster {
        "closeModal": () => Promise<void>;
        "confirmModal": () => Promise<void>;
        "customClass": string;
        "isClosable": boolean;
        "isConfirm": boolean;
        "message": string;
        "openModal": () => Promise<void>;
        "type": 'info' | 'success' |'failure' | 'warning';
    }
}
export interface StnButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLStnButtonElement;
}
export interface StnModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLStnModalElement;
}
export interface StnModalBottomCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLStnModalBottomElement;
}
export interface StnModalCenterCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLStnModalCenterElement;
}
export interface StnModalSlideCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLStnModalSlideElement;
}
export interface StnToasterCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLStnToasterElement;
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLStnButtonElementEventMap {
        "action": void;
    }
    interface HTMLStnButtonElement extends Components.StnButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLStnButtonElementEventMap>(type: K, listener: (this: HTMLStnButtonElement, ev: StnButtonCustomEvent<HTMLStnButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLStnButtonElementEventMap>(type: K, listener: (this: HTMLStnButtonElement, ev: StnButtonCustomEvent<HTMLStnButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLStnButtonElement: {
        prototype: HTMLStnButtonElement;
        new (): HTMLStnButtonElement;
    };
    interface HTMLStnModalElementEventMap {
        "action": void;
    }
    interface HTMLStnModalElement extends Components.StnModal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLStnModalElementEventMap>(type: K, listener: (this: HTMLStnModalElement, ev: StnModalCustomEvent<HTMLStnModalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLStnModalElementEventMap>(type: K, listener: (this: HTMLStnModalElement, ev: StnModalCustomEvent<HTMLStnModalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLStnModalElement: {
        prototype: HTMLStnModalElement;
        new (): HTMLStnModalElement;
    };
    interface HTMLStnModalBottomElementEventMap {
        "close": void;
    }
    interface HTMLStnModalBottomElement extends Components.StnModalBottom, HTMLStencilElement {
        addEventListener<K extends keyof HTMLStnModalBottomElementEventMap>(type: K, listener: (this: HTMLStnModalBottomElement, ev: StnModalBottomCustomEvent<HTMLStnModalBottomElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLStnModalBottomElementEventMap>(type: K, listener: (this: HTMLStnModalBottomElement, ev: StnModalBottomCustomEvent<HTMLStnModalBottomElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLStnModalBottomElement: {
        prototype: HTMLStnModalBottomElement;
        new (): HTMLStnModalBottomElement;
    };
    interface HTMLStnModalCenterElementEventMap {
        "close": void;
    }
    interface HTMLStnModalCenterElement extends Components.StnModalCenter, HTMLStencilElement {
        addEventListener<K extends keyof HTMLStnModalCenterElementEventMap>(type: K, listener: (this: HTMLStnModalCenterElement, ev: StnModalCenterCustomEvent<HTMLStnModalCenterElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLStnModalCenterElementEventMap>(type: K, listener: (this: HTMLStnModalCenterElement, ev: StnModalCenterCustomEvent<HTMLStnModalCenterElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLStnModalCenterElement: {
        prototype: HTMLStnModalCenterElement;
        new (): HTMLStnModalCenterElement;
    };
    interface HTMLStnModalSlideElementEventMap {
        "close": void;
        "confirm": void;
    }
    interface HTMLStnModalSlideElement extends Components.StnModalSlide, HTMLStencilElement {
        addEventListener<K extends keyof HTMLStnModalSlideElementEventMap>(type: K, listener: (this: HTMLStnModalSlideElement, ev: StnModalSlideCustomEvent<HTMLStnModalSlideElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLStnModalSlideElementEventMap>(type: K, listener: (this: HTMLStnModalSlideElement, ev: StnModalSlideCustomEvent<HTMLStnModalSlideElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLStnModalSlideElement: {
        prototype: HTMLStnModalSlideElement;
        new (): HTMLStnModalSlideElement;
    };
    interface HTMLStnToasterElementEventMap {
        "close": void;
        "confirm": void;
    }
    interface HTMLStnToasterElement extends Components.StnToaster, HTMLStencilElement {
        addEventListener<K extends keyof HTMLStnToasterElementEventMap>(type: K, listener: (this: HTMLStnToasterElement, ev: StnToasterCustomEvent<HTMLStnToasterElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLStnToasterElementEventMap>(type: K, listener: (this: HTMLStnToasterElement, ev: StnToasterCustomEvent<HTMLStnToasterElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLStnToasterElement: {
        prototype: HTMLStnToasterElement;
        new (): HTMLStnToasterElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "stn-button": HTMLStnButtonElement;
        "stn-modal": HTMLStnModalElement;
        "stn-modal-bottom": HTMLStnModalBottomElement;
        "stn-modal-center": HTMLStnModalCenterElement;
        "stn-modal-slide": HTMLStnModalSlideElement;
        "stn-toaster": HTMLStnToasterElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface StnButton {
        "action"?: EventEmitter<void>;
        "disabled"?: boolean;
        "icon"?: boolean;
        "label"?: string;
        "onAction"?: (event: StnButtonCustomEvent<void>) => void;
        "size"?: 'small' | 'medium' | 'large';
        "type"?: 'button' | 'submit';
        "variant"?: 'primary' | 'secondary' | 'success' | 'warning' | 'info' | 'light' | 'link' | 'outline' | 'danger';
    }
    interface StnModal {
        "buttons"?: string;
        "customeClass"?: string;
        "headerTitle"?: string;
        "isOpen"?: boolean;
        "onAction"?: (event: StnModalCustomEvent<void>) => void;
    }
    interface StnModalBottom {
        "headerTitle"?: string;
        "onClose"?: (event: StnModalBottomCustomEvent<void>) => void;
        "showFooter"?: boolean;
    }
    interface StnModalCenter {
        "headerTitle"?: string;
        "onClose"?: (event: StnModalCenterCustomEvent<void>) => void;
        "showFooter"?: boolean;
    }
    interface StnModalSlide {
        "headerTitle"?: string;
        "isConfirm"?: boolean;
        "onClose"?: (event: StnModalSlideCustomEvent<void>) => void;
        "onConfirm"?: (event: StnModalSlideCustomEvent<void>) => void;
        "showFooter"?: boolean;
    }
    interface StnToaster {
        "customClass"?: string;
        "isClosable"?: boolean;
        "isConfirm"?: boolean;
        "message"?: string;
        "onClose"?: (event: StnToasterCustomEvent<void>) => void;
        "onConfirm"?: (event: StnToasterCustomEvent<void>) => void;
        "type"?: 'info' | 'success' |'failure' | 'warning';
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "stn-button": StnButton;
        "stn-modal": StnModal;
        "stn-modal-bottom": StnModalBottom;
        "stn-modal-center": StnModalCenter;
        "stn-modal-slide": StnModalSlide;
        "stn-toaster": StnToaster;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "stn-button": LocalJSX.StnButton & JSXBase.HTMLAttributes<HTMLStnButtonElement>;
            "stn-modal": LocalJSX.StnModal & JSXBase.HTMLAttributes<HTMLStnModalElement>;
            "stn-modal-bottom": LocalJSX.StnModalBottom & JSXBase.HTMLAttributes<HTMLStnModalBottomElement>;
            "stn-modal-center": LocalJSX.StnModalCenter & JSXBase.HTMLAttributes<HTMLStnModalCenterElement>;
            "stn-modal-slide": LocalJSX.StnModalSlide & JSXBase.HTMLAttributes<HTMLStnModalSlideElement>;
            "stn-toaster": LocalJSX.StnToaster & JSXBase.HTMLAttributes<HTMLStnToasterElement>;
        }
    }
}
